WikiCore.Web/Models/ErrorViewModel.cs
using System;

namespace WikiCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WikiCore.Web/Models/WikiPageEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WikiCore.Models
{
    public class WikiPageEditModel
    {
        public string Title { get; set; }
        public string Markdown { get; set; }
    }
}

WikiCore.Web/Models/WikiPageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WikiCore.Lib.DTO;

namespace WikiCore.Models
{
    public class WikiPageModel
    {
      public   WikiPageDTO WikiPage { get; set; }
      public string EditUrl { get; set; }
    }
}

WikiCore.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WikiCore.Lib.BLL;
using WikiCore.Models;

namespace WikiCore.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        IWikiPageService service;
        public HomeController(IWikiPageService service)
        {
            this.service = service;
        }

        public IActionResult Index()
        {
            var result=service.GetAllPages(null, 0, int.MaxValue);
            return View(result);
        }
        
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WikiCore.Web/Controllers/WikiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WikiCore.Lib.BLL;
using WikiCore.Lib.BLL.BO;
using WikiCore.Lib.DAL;
using WikiCore.Lib.DTO;
using WikiCore.Models;

namespace WikiCore.Controllers
{
    [Authorize]
    public class WikiController : Controller
    {
        IWikiPageService service;
        public WikiController(IWikiPageService service)
        {
            this.service = service;
        }

        public IActionResult View(string slug, int? version=null)
        {
            WikiPageDTO page = null;
            if (version.HasValue)
            {
                page = service.GetPageRevision(slug, version.Value);
            }
            else
            {
                page = service.GetPage(slug);
            }

            if (page == null)
            {
                return Redirect(Request.Path + "/edit");
            }

            var model = new WikiPageModel()
            {
                WikiPage = page,
                EditUrl=Request.Scheme+"://"+(Request.Host+Request.Path+"/edit").Replace("//","/")
            };

            return View(model);
        }


        public IActionResult Edit(string slug)
        {
            WikiPageDTO page = service.GetPage(slug);
            WikiPageEditModel model = null;


            if (page == null)
            {
                model = new WikiPageEditModel()
                {
                    Title = slug,
                    Markdown = "## " + slug
                };
            }
            else
            {
                model = new WikiPageEditModel()
                {
                    Title = page.Title,
                    Markdown = page.BodyMarkDown
                };

            }
            return View(model);
        }

        public IActionResult Save(WikiPageEditModel item)
        {
            WikiPageBO bo = new WikiPageBO()
            {
                Title = item.Title,
                BodyMarkDown = item.Markdown
            };

            WikiPageDTO page = service.Save(bo);

            return Redirect("/wiki/" + page.Slug);
        }
    }
}

WikiCore.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

WikiCore.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using PagedList;
@using WikiCore.Lib.DTO;
@using WikiCore.Lib.Utilities;
@model IPagedList<WikiPageDTO>;


<h1> Wiki Page</h1>
<style>
    .list-group-item {
        cursor: pointer;
    }

        .list-group-item:hover {
            cursor: pointer;
            z-index: 2;
            color: #fff;
            background-color: #3495f3;
            border-color: #3495f3;
        }
</style>

<div class="panel panel-default">
    <div class="panel-body">
        <form asp-controller="Wiki" asp-action="Save" method="post">
            <div class="form-group row">
                <label for="Title" class="col-sm-2 col-form-label">New Page</label>
                <div class="col-sm-8">
                    <input placeholder="Enter title..gffg." class="form-control newtitle" id="Title" />
                </div>
                <div class="col-sm-2">
                    <button type="button" class="btn btn-primary" onclick="gotoEdit();">Save</button>
                </div>
            </div>

        </form>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-body">

        <div id="pages">
            <form>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input  placeholder="Search" class="form-control search" />
                    </div>
                    </div>
</form>
                <ul class="list list-group">
                    @foreach (var item in Model)
                    {
                        <li data-slug="@item.Slug" onclick="gotoView(this);" class="list-group-item">
                            <h3 class="title">@item.Title</h3>
                            <p class="body">@Html.Raw(MarkdownHelper.StripHTML(item.BodyHtml.Substring(0, 30)))</p>

                        </li>
                    }
                </ul>
            </div>
        </div>
</div>

<script src="//cdnjs.cloudflare.com/ajax/libs/list.js/1.5.0/list.min.js"></script>
<script>

    function gotoEdit() {
        var newtitle = $(".newtitle").val;
        var url = document.location + "/" + newtitle + "/edit";
        document.location.href = url;
    }

    function gotoView(element) {
        var slug = $(element).data("slug");
        var url = (document.location.href + "/wiki/" + slug);
        document.location.href = url;
    }

    var options = {
        valueNames: ['title', 'body']
    };

    var userList = new List('pages', options);
</script>

WikiCore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WikiCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">WikiCore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - WikiCore</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WikiCore.Web/Views/Wiki/Edit.cshtml
@model WikiPageEditModel

@{
    ViewData["Title"] = "Edit View";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

<h1> Edit @Model.Title </h1>

<form asp-controller="Wiki" asp-action="Save" method="post">

    <div class="form-group">
        <label for="Title">Title</label>
        <input asp-for="Title" placeholder="Title" class="form-control" />
        <small id="titleHelp" class="form-text text-muted">Enter Title.</small>
    </div>


    <div class="form-group">
        <label for="Markdown">Password</label>
        <textarea asp-for="Markdown"></textarea><br />
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
</form>





<script>
    var simplemde = new SimpleMDE({ element: document.getElementById("Markdown") });
</script>

WikiCore.Web/Views/Wiki/View.cshtml
@model WikiPageModel
@using Microsoft.AspNetCore.Http.Extensions

@{
    ViewData["Title"] = "Wiki View";
}




<div class="jumbotron jumbotron-fluid">

    <h1 class="display-4"> @Model.WikiPage.Title</h1>
    <p><a href="@Model.EditUrl">Edit</a></p>
    <hr class="my-4">
    <p>
        @Html.Raw(@Model.WikiPage.BodyHtml)
    </p>
</div>